### ISSUE TITLE
`manifest unknown`

### ISSUE THREAD

**Issue by utoni** [openwrt/gh-action-sdk#23]
I am using this pretty neat repository to build [https://github.com/utoni/nDPId](https://github.com/utoni/nDPId).

It worked until some recent changes. Github CI is reporting `manifest unknown`. But I have absolutely no clue what manifest and where I can find it.

**Comment by aparcar** [comment]
Fixed via https://github.com/utoni/nDPId/pull/18

**Comment by utoni** [comment]
Thank you @aparcar! Greetings from Leipzig to Leipzig. <3
