### ISSUE TITLE
How to add multiple feeds and test

### ISSUE THREAD

**Issue by smallprogram** [openwrt/gh-action-sdk#28]
I want to ask a question
I have two repositories, A and B. A is luci-app-A, and B is the packages that A depends on. The repository name of B is luci-app-A-Packages. Some of B's packages are not required by default. of.
How do I use gh-action-sdk to test pull requests in the B repository and test all packages in B
Can that friend give me an example? Thank you very much.

**Comment by smallprogram** [comment]
> You can define EXTRA_FEEDS which would contain feed A.
> 
> EXTRA_FEEDS: "src-git|feedA|https://github.org/yourproject/feed-a.git
> Since the CI would be added to feed B it's automatically included.
> 
> Now you have packages from both feeds available.

Thank you. I will try

**Comment by aparcar** [comment]
Please close this issue if you succeed.
