### ISSUE TITLE
Building OpenWrt packages fails for some architectures

### ISSUE THREAD

**Issue by utoni** [openwrt/gh-action-sdk#43]
I've noticed that some CI builds seem to fail for some architectures (`ubuntu-latest`, `x86_64` in that case, using `openwrt/gh-action-sdk@v7`):

```make
/builder/staging_dir/host/bin/fakeroot /builder/staging_dir/host/bin/bash /builder/scripts/ipkg-build -m "" /builder/build_dir/target-x86_64_musl/toolchain/ipkg-x86_64/libgcc /builder/bin/targets/x86/64/packages
/builder/staging_dir/host/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /builder/staging_dir/host/lib/libfakeroot.so)
make[2]: *** [Makefile:792: /builder/bin/targets/x86/64/packages/libgcc1_13.3.0-r4_x86_64.ipk] Error 1
```

**Comment by moetayuko** [comment]
the sdk is built with debian 12 since https://github.com/openwrt/buildbot/commit/3ac7d39bd4c364d76e78b3ba50c23a68e0b05c0f, but the docker image is still debian 11

**Comment by ynezz** [comment]
> /builder/staging_dir/host/bin/bash: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /builder/staging_dir/host/lib/libfakeroot.so)

Ugh, I'm wondering how this could've happened? 

> the sdk is built with debian 12 since https://github.com/openwrt/buildbot/commit/3ac7d39bd4c364d76e78b3ba50c23a68e0b05c0f, but the docker image is still debian 11

AFAIK we should be only using the Debian 12 based containers for the staging environment, for testing only. We shouldn't be using those on production buildbots.

**Comment by moetayuko** [comment]
> AFAIK we should be only using the Debian 12 based containers for the staging environment, for testing only. We shouldn't be using those on production buildbots.

does _staging environment_ include the snapshot branch? the glibc error is observed with these docker images, e.g. `openwrt/sdk:x86-64-main`

**Comment by utoni** [comment]
CI still fails with the same error

**Comment by moetayuko** [comment]
> CI still fails with the same error

you need to wait for the new images to be built.
