### ISSUE TITLE
always stops at stamp .package_compile with exit code 2

### ISSUE THREAD

**Issue by gretel** [openwrt/gh-action-sdk#48]
this is with `V: sc`:

```
...
make[2]: Leaving directory '/builder'
make[1]: *** [package/Makefile:179: /builder/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/builder'
make: *** [/builder/include/toplevel.mk:241: world] Error 2
Error: Process completed with exit code 2.
```

https://github.com/gretel/reticulum-openwrt/actions/runs/12094072394/job/33725724177

**Comment by gretel** [comment]
actual issue is `entrypoint.sh` logic "hiding" error messages due to `|` for return code handling.

did fork and [renovate](https://github.com/gretel/reticulum-openwrt/blob/main/entrypoint.sh) to fit my small usecase.

**Comment by aparcar** [comment]
Please feel free to create a PR
